# rollout-web-simple.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-web-simple
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: nginx
        image: nginx:1.24-alpine
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - analysis:
          templates:
          - templateName: web-health
      - setWeight: 50
      - pause: {duration: 30s}
      - setWeight: 80
      - pause: {duration: 30s}

---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: web-health
  namespace: default
spec:
  metrics:
  - name: health-check
    count: 5                    # Run 5 times
    interval: 10s               # Every 10 seconds
    successCondition: result == true
    failureLimit: 2             # Allow 2 failures
    provider:
      web:
        url: "http://nginx-service.default.svc.cluster.local/health"
        timeoutSeconds: 10
        jsonPath: "{$.healthy}"